services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      - "TZ=${TZ}"
      - "LC_ALL=${LC_ALL}"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "30"
    ports:
      - "${GITLAB_SSH_PORT}:22"
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
    volumes:
      - "${GITLAB_CONFIG_DIR}:/etc/gitlab"
      - "${GITLAB_DATA_DIR}:/var/opt/gitlab"
      - "${GITLAB_LOGS_DIR}:/var/log/gitlab"
